version: "3.9"

services:
    laravelapp:
        container_name: laravelapp
        image: sasacrow/laravelapp:1.0.5
        build: .
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db

    db:
        container_name: db
        image: mysql:8
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_DB: laravel_rest_api
        volumes:
            - mysqldata:/var/lib/mysql

volumes:
    mysqldata: {}
